//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountAuthorities = new HashSet<AccountAuthority>();
        }
    
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public UR.Common.Types.AccountType AccountType { get; set; }
        public Nullable<System.DateTime> FADateTime { get; set; }
        public string FAUser { get; set; }
        public Nullable<System.DateTime> LCDateTime { get; set; }
        public string LCUser { get; set; }
    
        public virtual ICollection<AccountAuthority> AccountAuthorities { get; set; }
    }
}
