//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountAuthorities = new HashSet<AccountAuthority>();
            this.SmsGroupAccounts = new HashSet<SmsGroupAccount>();
            this.FAParts = new HashSet<Part>();
            this.LCParts = new HashSet<Part>();
        }
    
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Common.Types.AccountType AccountType { get; set; }
        public Nullable<System.DateTime> FADateTime { get; set; }
        public string FAUser { get; set; }
        public Nullable<System.DateTime> LCDateTime { get; set; }
        public string LCUser { get; set; }
        public Nullable<int> MajorId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<AccountAuthority> AccountAuthorities { get; set; }
        public virtual Major Major { get; set; }
        public virtual ICollection<SmsGroupAccount> SmsGroupAccounts { get; set; }
        public virtual ICollection<Part> FAParts { get; set; }
        public virtual ICollection<Part> LCParts { get; set; }
    }
}
