
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class DutyTime
{

    public Common.Types.DutyTimeType Id { get; set; }

    public System.TimeSpan StartTime { get; set; }

    public System.TimeSpan EndTime { get; set; }

}

}
