//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Part = new HashSet<Part>();
        }
    
        public int Id { get; set; }
        public Common.Types.MachineSetType MachineSet { get; set; }
        public int MonitorTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual MonitorType MonitorType { get; set; }
        public virtual ICollection<Part> Part { get; set; }
    }
}
