//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Part = new HashSet<Part>();
        }
    
        public int Id { get; set; }
        public Common.Types.MachineSetType MachineSet { get; set; }
        public int MonitorTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual MonitorType MonitorType { get; set; }
        public virtual ICollection<Part> Part { get; set; }
    }
}
