//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogException
    {
        public int Id { get; set; }
        public string RequestInfo { get; set; }
        public string UserName { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public Nullable<System.DateTime> FADateTime { get; set; }
    }
}
