//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartSms
    {
        public int PartId { get; set; }
        public int GroupId { get; set; }
        public string Content { get; set; }
        public decimal HRecover { get; set; }
        public decimal LRecover { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual SmsGroup SmsGroup { get; set; }
    }
}
