//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.UltraRecord = new HashSet<UltraRecord>();
        }
    
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public string Name { get; set; }
        public string DataKey { get; set; }
        public string Unit { get; set; }
        public decimal L1 { get; set; }
        public Nullable<decimal> L2 { get; set; }
        public Nullable<decimal> L3 { get; set; }
        public decimal H1 { get; set; }
        public Nullable<decimal> H2 { get; set; }
        public Nullable<decimal> H3 { get; set; }
        public Nullable<int> MajorId { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> PL { get; set; }
        public bool SendSms { get; set; }
        public Nullable<int> UltraNum { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ICollection<UltraRecord> UltraRecord { get; set; }
        public virtual Major Major { get; set; }
        public virtual PartSms PartSm { get; set; }
    }
}
