
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Part
{

    public Part()
    {

        this.UltraRecord = new HashSet<UltraRecord>();

    }


    public int Id { get; set; }

    public int EquipmentId { get; set; }

    public string Name { get; set; }

    public string DataKey { get; set; }

    public string Unit { get; set; }

    public decimal L1 { get; set; }

    public decimal L2 { get; set; }

    public decimal L3 { get; set; }

    public decimal H1 { get; set; }

    public decimal H2 { get; set; }

    public decimal H3 { get; set; }

    public Nullable<int> MajorId { get; set; }

    public Nullable<decimal> PH { get; set; }

    public Nullable<decimal> PL { get; set; }

    public bool SendSms { get; set; }

    public int UltraNum { get; set; }



    public virtual Equipment Equipment { get; set; }

    public virtual ICollection<UltraRecord> UltraRecord { get; set; }

    public virtual Major Major { get; set; }

    public virtual PartSms PartSm { get; set; }

}

}
