//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartSms
    {
        public int PartId { get; set; }
        public int GroupId { get; set; }
        public string Content { get; set; }
        public decimal HRecover { get; set; }
        public decimal LRecover { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual SmsGroup SmsGroup { get; set; }
    }
}
