//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RtPoint
    {
        public int Id { get; set; }
        public string PointName { get; set; }
        public string Position { get; set; }
        public int TableType { get; set; }
        public int MachNO { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
    }
}
