//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsGroup
    {
        public SmsGroup()
        {
            this.PartSms = new HashSet<PartSms>();
            this.SmsGroupAccounts = new HashSet<SmsGroupAccount>();
            this.SmsLogs = new HashSet<SmsLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PartSms> PartSms { get; set; }
        public virtual ICollection<SmsGroupAccount> SmsGroupAccounts { get; set; }
        public virtual ICollection<SmsLog> SmsLogs { get; set; }
    }
}
