//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsLog
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int SmsType { get; set; }
        public Nullable<int> WarningType { get; set; }
        public string Content { get; set; }
        public bool IsSuccess { get; set; }
        public System.DateTime FADateTime { get; set; }
    
        public virtual SmsGroup SmsGroup { get; set; }
    }
}
