//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的�?
//
//    手动更改此文件可能会导致应用程序中发生异常行为�?
//    如果重新生成代码，则将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UltraRecord
    {
        public int Id { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int Duty { get; set; }
        public string UltraType { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> AvgValue { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> HasRemarks { get; set; }
        public Nullable<bool> IsProRecord { get; set; }
        public bool SmsFlag { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
