
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class UltraRecord
{

    public int Id { get; set; }

    public int PartId { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }

    public int Duty { get; set; }

    public string UltraType { get; set; }

    public decimal MinValue { get; set; }

    public decimal MaxValue { get; set; }

    public decimal AvgValue { get; set; }

    public System.DateTime StartTime { get; set; }

    public bool Flag { get; set; }

    public string Remarks { get; set; }

    public bool HasRemarks { get; set; }

    public bool IsProRecord { get; set; }



    public virtual Part Part { get; set; }

}

}
