

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccess
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class UltralReportsEntities : DbContext
{
    public UltralReportsEntities()
        : base("name=UltralReportsEntities")
    { 
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Account> Accounts { get; set; }

    public DbSet<AccountAuthority> AccountAuthorities { get; set; }

    public DbSet<Authority> Authorities { get; set; }

    public DbSet<LogException> LogExceptions { get; set; }

    public DbSet<LogOperation> LogOperations { get; set; }

    public DbSet<SmsGroup> SmsGroups { get; set; }

    public DbSet<SmsRecipient> SmsRecipients { get; set; }

    public DbSet<Equipment> Equipment { get; set; }

    public DbSet<MonitorType> MonitorType { get; set; }

    public DbSet<Part> Part { get; set; }

    public DbSet<UltraRecord> UltraRecord { get; set; }

    public DbSet<Major> Majors { get; set; }

    public DbSet<Shift> Shifts { get; set; }

    public DbSet<Schedule> Schedules { get; set; }

}

}

